language: go
go: 
 - 1.1
 - 1.2
 - release
 - tip
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas-base-dev liblinear-dev
install:
 - go get github.com/smartystreets/goconvey/convey
 - go get -v ./...
